spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_quartz_job
    username: root
    password: 123456
  jpa:
#    properties:
#      hibernate:
#        dialect: "org.hibernate.dialect.MySQL5Dialect"
#        id:
#          new_generator_mappings: true
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true